FROM centos:centos7

MAINTAINER Houssem BELHADJ AHMED <houssem@belhadjahmed.com>

RUN yum install -y java-1.8.0-openjdk.x86_64

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]

